ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "allowPublicInvites" BOOLEAN;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "phoneE164" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "phoneVerifiedAt" TIMESTAMPTZ;
