// backend/src/services/cloudinary.js
const cloudinary = require('cloudinary').v2;
const multer = require('multer');
const { CloudinaryStorage } = require('multer-storage-cloudinary');

cloudinary.config({
  cloud_name: process.env.CLOUDINARY_CLOUD_NAME,
  api_key: process.env.CLOUDINARY_API_KEY,
  api_secret: process.env.CLOUDINARY_API_SECRET,
});

const OUTINGS_FOLDER = process.env.CLOUDINARY_OUTINGS_FOLDER || 'outings';
const THUMBS_FOLDER = process.env.CLOUDINARY_THUMBS_FOLDER || 'thumbs';

const storage = new CloudinaryStorage({
  cloudinary,
  params: async (_req, file) => {
    // NOTE: client already compresses; this just stores what we receive.
    return {
      folder: OUTINGS_FOLDER,
      resource_type: 'image',
      allowed_formats: ['jpg', 'jpeg', 'png', 'webp', 'heic', 'heif'],
      // public_id can be autogenerated; leaving blank is fine.
      // You can add tags here if desired:
      // tags: ['outing'],
    };
  },
});

const uploader = multer({ storage });

async function deleteByPublicId(publicId) {
  return cloudinary.uploader.destroy(publicId, {
    resource_type: 'image',
    invalidate: true,
  });
}

function isThumbPublicId(publicId) {
  // If we store thumbnails under thumbs/..., don’t re-process them.
  return typeof publicId === 'string' && publicId.startsWith(`${THUMBS_FOLDER}/`);
}

function buildThumbPublicId(originalPublicId) {
  // Preserve original path structure under thumbs/
  // e.g. outings/abc123 -> thumbs/outings/abc123
  const clean = String(originalPublicId).replace(/^\/+/, '');
  return `${THUMBS_FOLDER}/${clean}`;
}

function transformedUrlFromPublicId(publicId, { w = 720, h = 720 } = {}) {
  // Cloudinary URL for a small “thumbnail-only” asset
  return cloudinary.url(publicId, {
    secure: true,
    transformation: [
      { fetch_format: 'auto' },
      { quality: 'auto:eco' },
      { width: w, height: h, crop: 'fill', gravity: 'auto' },
    ],
  });
}

/**
 * Creates a NEW thumbnail asset in Cloudinary based on an existing asset publicId.
 * Strategy:
 *  - create a transformed URL (small size)
 *  - upload that URL as a new asset under thumbs/
 */
async function createThumbnailAssetFromPublicId(originalPublicId, opts = {}) {
  const thumbPublicId = buildThumbPublicId(originalPublicId);
  const thumbUrl = transformedUrlFromPublicId(originalPublicId, {
    w: opts.thumbW ?? 720,
    h: opts.thumbH ?? 720,
  });

  // Upload from remote URL → new stored asset
  const result = await cloudinary.uploader.upload(thumbUrl, {
    public_id: thumbPublicId,
    overwrite: true,
    resource_type: 'image',
    invalidate: true,
  });

  return result;
}

module.exports = {
  uploader,
  deleteByPublicId,

  // Retention helpers
  isThumbPublicId,
  createThumbnailAssetFromPublicId,
};
